//
//C++ header file generated by UMiLacz v 1.0
//
//@Autors: Alexander Myronov & Izabela Orlowska
//
#include <MyClass2.h>

class MyClass: public MyClass2
{
	//default:
	private:
		myType* attributeNb;
		static  pair< int, myType* > foo(int param1, myType* param2);
	protected:
		string name;
	public:
		string foo2();
};
