//
//Java file generated by UMiLacz v 1.0
//
//@Autors: Alexander Myronov & Izabela Orlowska
//

private class MyClass2 {
	//attributes
	private myType* attributeNb;
	protected string name;

	//methods
	private  static  pair< int, myType* > foo(int param1, myType* param2);
	public   string foo2();
};
